engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**/*
exclude_paths:
- test/**/*
